import type { Lead } from "./types";

/**
 * Shown until AIRTABLE_API_KEY + AIRTABLE_BASE_ID are set. Lets the site be
 * built, reviewed, and demoed before the n8n workflow has produced real rows.
 *
 * Deliberately kept small enough that every niche/source group in
 * Performance Insights reads as "Insufficient Data" — that's the honest,
 * correct state for a system this new, and padding the sample set just to
 * make a "Promising" badge visible in a demo would undercut the entire
 * point of Role 5. Real data will grow past that on its own.
 */
const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();
const daysAgo = (d: number) => hoursAgo(d * 24);

export const sampleLeads: Lead[] = [
  {
    id: "sample-1",
    title: "Clinical Content Writer for Metabolic Health Platform",
    clientName: "Vero Health (telehealth startup)",
    sourceUrl: "https://example.com/jobs/clinical-writer-1",
    sourcePlatform: "Upwork",
    needSummary:
      "Ongoing patient-facing articles on metabolic conditions; wants a writer who can read clinical literature directly.",
    rawDescription:
      "We're a telehealth platform looking for a long-term content partner to write patient education material on metabolic health. Must be comfortable reading peer-reviewed studies and translating findings for a general audience. Nutrition background strongly preferred.",
    budgetSignal: "$60-80/hr, ongoing",
    status: "Approved",
    dateFound: hoursAgo(3),
    closedAt: null,
    repliedAt: null,
    conversationAt: null,
    callBookedAt: null,
    proposalAt: null,
    skillFitScore: 9,
    valueScore: 8,
    confidence: "High",
    scoreReasoning:
      "Directly requires nutrition science literacy and primary-source reading — a strong match for an MSc-credentialed writer, not generic content work.",
    recommendedAction: "Apply",
    nicheTag: "health-nutrition",
    urgency: "High",
    verifiedFacts: [
      "Posted by a telehealth platform, ongoing relationship (not one-off)",
      "Payment verified, 8 prior hires on Upwork",
    ],
    inferredSignals: [
      "Retainer-shaped ask ('long-term content partner') suggests recurring revenue, not a single invoice",
    ],
    unknownFactors: ["Exact monthly volume/word count not stated"],
    positiveSignals: ["Core-pillar fit", "Ongoing, not one-off", "Payment verified"],
    negativeSignals: [],
    recommendedService: "Ongoing content retainer",
    outreachAngle:
      "Lead with the MSc and comfort reading primary literature directly — this client explicitly asked for that, most applicants won't have it.",
    outreachDraft:
      "Hi — I have an MSc in Human Nutrition and Dietetics and regularly read primary studies rather than working from secondary summaries, which sounded like exactly what you're after for the metabolic health content. Happy to send a short writing sample on a related topic if useful — what's the best next step on your end?",
    contactName: "",
    contactEmail: "",
    lastContact: null,
    followUpDue: null,
    notes: "",
    revenue: null,
    lossReason: "",
    isRecurring: false,
    estimatedValue: null,
    proposedValue: null,
    scheduledCallAt: null,
    calendarEventId: null,
  },
  {
    id: "sample-2",
    title: "White Paper: Gut Microbiome & Supplement Efficacy",
    clientName: "NutraLine Sciences",
    sourceUrl: "https://example.com/jobs/white-paper-2",
    sourcePlatform: "Company Site",
    needSummary:
      "One-off 5,000 word white paper synthesizing microbiome research for an advisory board.",
    rawDescription:
      "Seeking a freelance writer to produce a white paper reviewing current research on gut microbiome and supplement efficacy, for internal advisory board use. Must cite primary literature and note study limitations.",
    budgetSignal: "$1,800 flat",
    status: "Contacted",
    dateFound: hoursAgo(20),
    closedAt: null,
    repliedAt: null,
    conversationAt: null,
    callBookedAt: null,
    proposalAt: null,
    skillFitScore: 8,
    valueScore: 6,
    confidence: "Medium",
    scoreReasoning:
      "Literature synthesis with explicit evidence-grading requirement — squarely in her research-writing specialism.",
    recommendedAction: "Apply",
    nicheTag: "health-nutrition",
    urgency: "Medium",
    verifiedFacts: ["5,000 word white paper, $1,800 flat, one-off"],
    inferredSignals: ["Advisory-board audience suggests a more rigorous, better-paying client type"],
    unknownFactors: ["Whether this could lead to repeat white-paper work"],
    positiveSignals: ["Clear scope and budget stated upfront"],
    negativeSignals: ["One-off, no stated recurring potential"],
    recommendedService: "One-off white paper",
    outreachAngle: "",
    outreachDraft: "",
    contactName: "",
    contactEmail: "",
    lastContact: daysAgo(1),
    followUpDue: daysAgo(-6),
    notes: "Sent proposal referencing her MSc thesis topic (insulin resistance).",
    revenue: null,
    lossReason: "",
    isRecurring: false,
    estimatedValue: null,
    proposedValue: null,
    scheduledCallAt: null,
    calendarEventId: null,
  },
  {
    id: "sample-3",
    title: "SaaS Onboarding Explainer Series",
    clientName: "Statuly (B2B SaaS)",
    sourceUrl: "https://example.com/jobs/saas-3",
    sourcePlatform: "Upwork",
    needSummary: "Recurring plain-language explainer articles for a B2B SaaS product's users.",
    rawDescription:
      "SaaS company needs a writer to turn product features into plain-language explainer articles for our users. Looking for someone who can make a technical product make sense to a non-technical buyer.",
    budgetSignal: "Not specified",
    status: "Replied",
    dateFound: daysAgo(2),
    closedAt: null,
    repliedAt: daysAgo(1),
    conversationAt: null,
    callBookedAt: null,
    proposalAt: null,
    skillFitScore: 7,
    valueScore: 5,
    confidence: "Medium",
    scoreReasoning:
      "Tech/SaaS explainer writing matching her stated specialism, though budget is unclear and worth confirming before proposing.",
    recommendedAction: "Apply",
    nicheTag: "tech-saas-b2b",
    urgency: "Medium",
    verifiedFacts: ["Recurring ('explainer series'), no budget figure given"],
    inferredSignals: ["Likely ongoing work given 'series' framing"],
    unknownFactors: ["Budget entirely unstated — a real risk of low-pay client"],
    positiveSignals: ["Core-pillar fit (SaaS/B2B explainer)"],
    negativeSignals: ["No budget signal"],
    recommendedService: "",
    outreachAngle: "",
    outreachDraft: "",
    contactName: "",
    contactEmail: "",
    lastContact: daysAgo(1.5),
    followUpDue: null,
    notes: "They replied asking for 2 writing samples — sent Tuesday.",
    revenue: null,
    lossReason: "",
    isRecurring: false,
    estimatedValue: null,
    proposedValue: null,
    scheduledCallAt: null,
    calendarEventId: null,
  },
  {
    id: "sample-4",
    title: "SEO Blog Writer — Home & Lifestyle",
    clientName: "CasaBlog Media",
    sourceUrl: "https://example.com/jobs/generic-4",
    sourcePlatform: "Upwork",
    needSummary: "Generic SEO content across home decor, lifestyle, and travel topics.",
    rawDescription:
      "Content mill looking for fast turnaround SEO writers across multiple lifestyle verticals. No subject-matter expertise required, volume-based pay.",
    budgetSignal: "$0.03/word",
    status: "Passed",
    dateFound: daysAgo(2),
    closedAt: daysAgo(1.9),
    repliedAt: null,
    conversationAt: null,
    callBookedAt: null,
    proposalAt: null,
    skillFitScore: 2,
    valueScore: 1,
    confidence: "High",
    scoreReasoning:
      "No health, tech, or research component and pay signals a content-mill model — poor fit for a credentialed specialist.",
    recommendedAction: "Skip",
    nicheTag: "general-content",
    urgency: "Low",
    verifiedFacts: ["$0.03/word, multi-vertical, volume-based"],
    inferredSignals: [],
    unknownFactors: [],
    positiveSignals: [],
    negativeSignals: ["Content-mill pay rate", "No subject-matter fit"],
    recommendedService: "",
    outreachAngle: "",
    outreachDraft: "",
    contactName: "",
    contactEmail: "",
    lastContact: null,
    followUpDue: null,
    notes: "",
    revenue: null,
    lossReason: "",
    isRecurring: false,
    estimatedValue: null,
    proposedValue: null,
    scheduledCallAt: null,
    calendarEventId: null,
  },
  {
    id: "sample-5",
    title: "Ongoing Nutrition Content — Referral from Priya",
    clientName: "Sequoia Wellness Clinic",
    sourceUrl: "",
    sourcePlatform: "Warm Network",
    needSummary:
      "Priya (past client) referred their clinic's marketing lead, who wants a recurring nutrition-content writer.",
    rawDescription:
      "Warm intro via a past client — no formal posting. Clinic wants monthly patient-education content, evidence-based.",
    budgetSignal: "$2,500/mo (discussed on intro call)",
    status: "Won",
    dateFound: daysAgo(20),
    closedAt: daysAgo(3),
    repliedAt: daysAgo(19),
    conversationAt: daysAgo(17),
    callBookedAt: daysAgo(15),
    proposalAt: daysAgo(10),
    skillFitScore: 0,
    valueScore: 0,
    confidence: "Low",
    scoreReasoning: "",
    recommendedAction: "Apply",
    nicheTag: "health-nutrition",
    urgency: "High",
    verifiedFacts: [],
    inferredSignals: [],
    unknownFactors: [],
    positiveSignals: [],
    negativeSignals: [],
    recommendedService: "Ongoing content retainer",
    outreachAngle: "",
    outreachDraft: "",
    contactName: "Marcus (Marketing Lead)",
    contactEmail: "marcus@example.com",
    lastContact: daysAgo(19),
    followUpDue: null,
    notes: "Closed on intro call — first invoice sent.",
    revenue: 2500,
    lossReason: "",
    isRecurring: false,
    estimatedValue: null,
    proposedValue: null,
    scheduledCallAt: null,
    calendarEventId: null,
  },
  {
    id: "sample-6",
    title: "AI Feature Launch — Blog + Landing Page Copy",
    clientName: "Fintra (fintech SaaS)",
    sourceUrl: "https://example.com/jobs/fintech-6",
    sourcePlatform: "Company Site",
    needSummary: "Launch content for a new AI-powered fraud-detection feature.",
    rawDescription:
      "Fintech company launching an AI fraud-detection feature needs a blog post and landing page copy that explains the technology to non-technical SMB owners without oversimplifying the risk model.",
    budgetSignal: "$900 flat for both pieces",
    status: "Call Booked",
    dateFound: daysAgo(6),
    closedAt: null,
    repliedAt: daysAgo(5),
    conversationAt: daysAgo(4),
    callBookedAt: daysAgo(2),
    proposalAt: null,
    skillFitScore: 8,
    valueScore: 6,
    confidence: "Medium",
    scoreReasoning: "Tech/B2B explainer work for a non-expert audience — core Pillar 2 fit.",
    recommendedAction: "Apply",
    nicheTag: "tech-saas-b2b",
    urgency: "High",
    verifiedFacts: ["Two deliverables, $900 flat, explicit audience (SMB owners)"],
    inferredSignals: ["Launch timing suggests urgency and possible follow-on work post-launch"],
    unknownFactors: ["Whether there's a content need beyond this one launch"],
    positiveSignals: ["Clear scope and budget", "Strong pillar fit"],
    negativeSignals: [],
    recommendedService: "One-off launch content",
    outreachAngle: "",
    outreachDraft: "",
    contactName: "Dana (Head of Content)",
    contactEmail: "",
    lastContact: daysAgo(4),
    followUpDue: daysAgo(-3),
    notes: "Call booked for Thursday to discuss scope.",
    revenue: null,
    lossReason: "",
    isRecurring: false,
    estimatedValue: null,
    proposedValue: null,
    scheduledCallAt: null,
    calendarEventId: null,
  },
  {
    id: "sample-7",
    title: "Compliance Explainer Series — Legal-Tech SaaS",
    clientName: "Statuly (legal-tech SaaS)",
    sourceUrl: "https://example.com/jobs/legal-7",
    sourcePlatform: "Upwork",
    needSummary: "Recurring plain-language compliance articles for a legal SaaS product's users.",
    rawDescription:
      "Legal-tech company needs a writer to turn regulatory frameworks into plain-language blog posts for our SaaS users. No legal advice, just accurate explainers.",
    budgetSignal: "$400/article, 4/month",
    status: "Lost",
    dateFound: daysAgo(14),
    closedAt: daysAgo(8),
    repliedAt: daysAgo(13),
    conversationAt: daysAgo(11),
    callBookedAt: null,
    proposalAt: daysAgo(9),
    skillFitScore: 7,
    valueScore: 6,
    confidence: "Medium",
    scoreReasoning: "Adjacent tech-explainer fit, though outside her two stated core pillars.",
    recommendedAction: "Consider",
    nicheTag: "tech-saas-b2b",
    urgency: "Medium",
    verifiedFacts: ["4 articles/month, $400/article"],
    inferredSignals: [],
    unknownFactors: [],
    positiveSignals: ["Recurring, budget stated"],
    negativeSignals: [],
    recommendedService: "",
    outreachAngle: "",
    outreachDraft: "",
    contactName: "",
    contactEmail: "",
    lastContact: daysAgo(13),
    followUpDue: null,
    notes: "Went with an in-house writer instead.",
    revenue: null,
    lossReason: "Client hired in-house instead of freelance",
    isRecurring: false,
    estimatedValue: null,
    proposedValue: null,
    scheduledCallAt: null,
    calendarEventId: null,
  },
  {
    id: "sample-8",
    title: "LinkedIn contact — VP Content at a health-tech startup",
    clientName: "Renew Health",
    sourceUrl: "",
    sourcePlatform: "LinkedIn",
    needSummary: "Connected after commenting on her post about evidence-based content; mentioned they're expanding their blog.",
    rawDescription: "",
    budgetSignal: "Not specified",
    status: "Discovered",
    dateFound: hoursAgo(30),
    closedAt: null,
    repliedAt: null,
    conversationAt: null,
    callBookedAt: null,
    proposalAt: null,
    skillFitScore: 0,
    valueScore: 0,
    confidence: "Low",
    scoreReasoning: "",
    recommendedAction: "Consider",
    nicheTag: "",
    urgency: "Medium",
    verifiedFacts: [],
    inferredSignals: [],
    unknownFactors: [],
    positiveSignals: [],
    negativeSignals: [],
    recommendedService: "",
    outreachAngle: "",
    outreachDraft: "",
    contactName: "",
    contactEmail: "",
    lastContact: null,
    followUpDue: null,
    notes: "Manually added, not yet analyzed — use the Analyze button.",
    revenue: null,
    lossReason: "",
    isRecurring: false,
    estimatedValue: null,
    proposedValue: null,
    scheduledCallAt: null,
    calendarEventId: null,
  },
  {
    id: "sample-9",
    title: "Agency partner — subcontract health content",
    clientName: "Meridian Health Marketing (agency)",
    sourceUrl: "",
    sourcePlatform: "Agency",
    needSummary: "Boutique agency that places credentialed writers with pharma/health clients — introduced by a colleague.",
    rawDescription: "",
    budgetSignal: "Varies by client, agency-negotiated",
    status: "Discovered",
    dateFound: hoursAgo(50),
    closedAt: null,
    repliedAt: null,
    conversationAt: null,
    callBookedAt: null,
    proposalAt: null,
    skillFitScore: 0,
    valueScore: 0,
    confidence: "Low",
    scoreReasoning: "",
    recommendedAction: "Consider",
    nicheTag: "",
    urgency: "Medium",
    verifiedFacts: [],
    inferredSignals: [],
    unknownFactors: [],
    positiveSignals: [],
    negativeSignals: [],
    recommendedService: "",
    outreachAngle: "",
    outreachDraft: "",
    contactName: "",
    contactEmail: "",
    lastContact: null,
    followUpDue: null,
    notes: "Not yet analyzed.",
    revenue: null,
    lossReason: "",
    isRecurring: false,
    estimatedValue: null,
    proposedValue: null,
    scheduledCallAt: null,
    calendarEventId: null,
  },
];
